groups:
    - bash
#    - wijs
recipes:
    global:
#         - applications::composer
    mac_os_x:
        - osxdefaults::set_computer_name
        - osxdefaults::set_terminal_profile
        - applications::sublime_text_3
attributes:
    osxdefaults:
        computername: Bert
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - pwgen
            - htop-osx
            - git-flow
            - mtr
        cask_apps:
            - onepassword
            - dropbox
            - evernote
            - alfred
            - spotify
            - sequel-pro
            - vmware-fusion
            - virtualbox
            - vagrant
            - appcleaner
            - skitch
            - skype
            - transmit
